// CDS — Peak Load Test
// Multiplies production rates by PEAK_MULTIPLIER (default 3x)
// AUTO-GENERATED by runner/generate.js
// Run: k6 run -e PEAK_MULTIPLIER=3 apps/cds/scripts/peak-load.js

import http from 'k6/http'
import { check } from 'k6'

// ── Config ─────────────────────────────────────────────────────
const BASE_URL = __ENV.BASE_URL || 'https://uat-cds.tricogdev.net'
const TEST_EMAIL = __ENV.TEST_EMAIL || ''
const TEST_PASSWORD = __ENV.TEST_PASSWORD || ''
const PEAK_MULTIPLIER = parseInt(__ENV.PEAK_MULTIPLIER || '3')

const AUTH_HEADERS = {
  'Accept': 'application/json, text/plain, */*',
  'Content-Type': 'application/json;charset=UTF-8',
  'appname': 'CDS',
  'lang': 'en',
}

// ── Options — 3x production rates ─────────────────────────────
// PLACEHOLDER — runner/generate.js replaces scenarios with peak rates
export const options = {
  scenarios: {},
  thresholds: {
    http_req_failed: ['rate<0.10'],
    http_req_duration: ['p(95)<5000', 'p(99)<10000'],
  },
}

export function setup() {
  const res = http.post(
    `${BASE_URL}/api/login`,
    JSON.stringify({ username: TEST_EMAIL, password: TEST_PASSWORD }),
    { headers: AUTH_HEADERS }
  )
  check(res, { '[cds] login ok': (r) => r.status === 200 })
  return { token: res.json('token') }
}
